"""KnowledgeRegistry — aggregate metadata for multiple mrag KB projects.

`knowledge_registry.yaml` lives under a root directory containing several mrag
KB project subdirectories. It is generated by `mrag registry generate` from
each subdirectory's `kb_information.yaml` and `mrag.yaml`, and is read by
external agents (Agentic RAG workflows) to discover and select KBs.

Path semantics: each `knowledge_bases[].path` is **relative to the directory
containing the registry file itself** and emitted in POSIX form (./kb-device).
This makes the registry portable across machines and directory moves.

See:
  - dev_docs/01_EXTENSION_STAGE_1/MRAG_KB_INFORMATION_INIT_SPEC.md §15
  - dev_docs/01_EXTENSION_STAGE_1/DESIGN_V18_INSPECT_REGISTRY.md §2-§3.2
"""
from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, field_validator

from mrag.config.kb_info import KbInformationConfig


REGISTRY_FILENAME = "knowledge_registry.yaml"

_DEFAULT_SELECTION_POLICY = (
    "Select the most relevant knowledge base based on the user's question. "
    "If the question spans multiple domains, search multiple knowledge bases."
)

_DEFAULT_SEARCH_COMMAND_TEMPLATE = (
    'cd {path}\n'
    'mrag search "{query}" --profile {profile} --json\n'
)


class RegistryAgentInstructions(BaseModel):
    selection_policy: str = _DEFAULT_SELECTION_POLICY
    search_command_template: str = _DEFAULT_SEARCH_COMMAND_TEMPLATE


class RegistryKnowledgeBase(BaseModel):
    id: str
    path: str
    name: str
    description: str = ""
    tags: list[str] = Field(default_factory=list)
    best_for: list[str] = Field(default_factory=list)
    avoid_for: list[str] = Field(default_factory=list)
    preferred_profiles: list[str] = Field(default_factory=lambda: ["default"])
    example_queries: list[str] = Field(default_factory=list)

    @field_validator("id")
    @classmethod
    def _validate_id(cls, v: str) -> str:
        if not v:
            raise ValueError("knowledge_bases[].id must not be empty")
        return v

    @field_validator("path")
    @classmethod
    def _validate_path(cls, v: str) -> str:
        if not v:
            raise ValueError("knowledge_bases[].path must not be empty")
        return v

    @field_validator("name")
    @classmethod
    def _validate_name(cls, v: str) -> str:
        if not v:
            raise ValueError("knowledge_bases[].name must not be empty")
        return v


class KnowledgeRegistry(BaseModel):
    """Top-level knowledge_registry.yaml schema (version 1)."""

    version: Literal[1] = 1
    generated_at: str
    agent_instructions: RegistryAgentInstructions = Field(
        default_factory=RegistryAgentInstructions
    )
    knowledge_bases: list[RegistryKnowledgeBase] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Construction helpers
# ---------------------------------------------------------------------------


def now_utc_iso() -> str:
    """Return current UTC time as an ISO 8601 string (seconds precision)."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def to_relative_posix_path(kb_dir: Path, registry_dir: Path) -> str:
    """Build the POSIX relative path used in the registry's `path` field.

    Uses `os.path.relpath` so traversal upward via `..` is supported (allowing
    the registry to be written to a sibling/parent dir relative to the KB).
    The result is always prefixed with `./` for simple subdirs, or starts
    with `../` for upward traversal.
    """
    rel = os.path.relpath(
        Path(kb_dir).resolve(),
        Path(registry_dir).resolve(),
    )
    # Convert to POSIX form (Windows: \ → /)
    rel_posix = Path(rel).as_posix()
    if not rel_posix.startswith(".."):
        rel_posix = "./" + rel_posix
    return rel_posix


def from_kb_information(
    kb_info: KbInformationConfig,
    relative_path: str,
) -> RegistryKnowledgeBase:
    """Convert a project's kb_information.yaml + relative path into a registry entry."""
    return RegistryKnowledgeBase(
        id=kb_info.knowledge_base.id,
        path=relative_path,
        name=kb_info.knowledge_base.name,
        description=kb_info.knowledge_base.description,
        tags=list(kb_info.agent_usage.tags),
        best_for=list(kb_info.agent_usage.best_for),
        avoid_for=list(kb_info.agent_usage.avoid_for),
        preferred_profiles=list(kb_info.agent_usage.preferred_profiles),
        example_queries=list(kb_info.agent_usage.example_queries),
    )


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------


def registry_path(root_dir: Path) -> Path:
    return Path(root_dir) / REGISTRY_FILENAME


def load_registry(path: Path) -> KnowledgeRegistry:
    """Read and validate a knowledge_registry.yaml file."""
    if not Path(path).exists():
        raise FileNotFoundError(f"knowledge_registry.yaml not found at {path}")
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    return KnowledgeRegistry(**data)


def _str_presenter(dumper: yaml.Dumper, value: str) -> Any:
    """Use literal block style for multi-line strings (improves readability of
    the registry's agent_instructions section)."""
    if "\n" in value:
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", value)


class _RegistryDumper(yaml.SafeDumper):
    pass


_RegistryDumper.add_representer(str, _str_presenter)


def dump_registry(registry: KnowledgeRegistry, path: Path) -> Path:
    """Write a knowledge_registry.yaml file to disk; returns the written path."""
    data = registry.model_dump()
    Path(path).write_text(
        yaml.dump(
            data,
            Dumper=_RegistryDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            width=120,
        ),
        encoding="utf-8",
    )
    return Path(path)


def registry_json_schema() -> dict[str, Any]:
    """Return the JSON Schema for the knowledge_registry.yaml file."""
    return KnowledgeRegistry.model_json_schema()


__all__ = [
    "REGISTRY_FILENAME",
    "KnowledgeRegistry",
    "RegistryAgentInstructions",
    "RegistryKnowledgeBase",
    "dump_registry",
    "from_kb_information",
    "load_registry",
    "now_utc_iso",
    "registry_json_schema",
    "registry_path",
    "to_relative_posix_path",
]
